var coordData = {"type":"FeatureCollection","features":[

{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Saint-Benoît sur loire ","occ":10}, "geometry": {"coordinates": [2.308, 47.81 ], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Gand","occ":5}, "geometry": {"coordinates": [3.7303, 51.0500], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Quedlinburg","occ":6}, "geometry": {"coordinates": [11.1414, 51.7921], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Hildesheim","occ":5}, "geometry": {"coordinates": [9.9580, 52.1548], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Passau","occ":6}, "geometry": {"coordinates": [13.4319, 48.5667], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Reichenau","occ":5}, "geometry": {"coordinates": [9.0609, 47.6980], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Lobbes","occ":6}, "geometry": {"coordinates": [4.2652, 50.3455], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"S. Blasien","occ":5}, "geometry": {"coordinates": [8.1281, 47.7601], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Gembloux","occ":6}, "geometry": {"coordinates": [4.6920, 50.5600], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Brauweiler","occ":5}, "geometry": {"coordinates": [6.7878, 50.9589], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Liège","occ":6}, "geometry": {"coordinates": [5.5697, 50.6330], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Augsbourg","occ":5}, "geometry": {"coordinates": [10.8978, 48.3705], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Poitiers","occ":6}, "geometry": {"coordinates": [0.3404, 46.5802], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Milan","occ":5}, "geometry": {"coordinates": [9.1900, 45.4642], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Hautmont","occ":6}, "geometry": {"coordinates": [3.9171, 50.2470], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Prague","occ":5}, "geometry": {"coordinates": [14.4378, 50.0755], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Reinhardsbrunn","occ":6}, "geometry": {"coordinates": [10.5541, 50.8711], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Melk","occ":5}, "geometry": {"coordinates": [15.3500, 48.2265], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"S. Evroult","occ":6}, "geometry": {"coordinates": [0.4601, 48.7909], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Olmütz","occ":8}, "geometry": {"coordinates": [17.2509, 49.5938], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Vérone","occ":6}, "geometry": {"coordinates": [10.9916, 45.4384], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Sazawa","occ":5}, "geometry": {"coordinates": [14.8967, 49.8716], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"S. Omer","occ":8}, "geometry": {"coordinates": [2.2522, 50.7501], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Auxerre","occ":6}, "geometry": {"coordinates": [3.5738, 47.7982], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Reims","occ":5}, "geometry": {"coordinates": [4.0317, 49.2583], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Cologne","occ":8}, "geometry": {"coordinates": [6.9603, 50.9375], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Le Bec","occ":6}, "geometry": {"coordinates": [0.7227, 49.2308], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Strasbourg","occ":5}, "geometry": {"coordinates": [7.7521, 48.5734], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Pise","occ":8}, "geometry": {"coordinates": [10.4017, 43.7228], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Utrecht","occ":6}, "geometry": {"coordinates": [5.1214, 52.0907], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Kremsmünster","occ":5}, "geometry": {"coordinates": [14.1262, 48.0544], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Klosterneuburg","occ":8}, "geometry": {"coordinates": [16.3238, 48.3099], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Nîmes","occ":6}, "geometry": {"coordinates": [4.3601, 43.8367], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Glogau","occ":5}, "geometry": {"coordinates": [16.0847, 51.6636], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Merano","occ":8}, "geometry": {"coordinates": [11.1605, 46.6618], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Lichtensteig","occ":6}, "geometry": {"coordinates": [9.0877, 47.3239], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Viktring","occ":5}, "geometry": {"coordinates": [14.2755, 46.5919], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Lucerne","occ":8}, "geometry": {"coordinates": [8.3093, 47.0502], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Padoue","occ":6}, "geometry": {"coordinates": [11.8768, 45.4064], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Foligno","occ":5}, "geometry": {"coordinates": [12.7015, 42.9509], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Cesena","occ":5}, "geometry": {"coordinates": [12.2464, 44.1396], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Tournai","occ":8}, "geometry": {"coordinates": [3.3881, 50.6055], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Opatowitz ","occ":6}, "geometry": {"coordinates": [16.67942, 49.61264], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Narbonne","occ":5}, "geometry": {"coordinates": [3.0031, 43.1843], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Paris","occ":5}, "geometry": {"coordinates": [2.3522, 48.8566], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Toulouse","occ":8}, "geometry": {"coordinates": [1.4442, 43.6047], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Montpellier ","occ":6}, "geometry": {"coordinates": [3.8767, 43.6108], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Metz","occ":5}, "geometry": {"coordinates": [6.1757, 49.1193], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Mersebourg","occ":8}, "geometry": {"coordinates": [11.991746, 51.356328], "type": "Point"}}]}

]};

