var dataPhenomenes = {"type":"FeatureCollection","features":[

{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Saint-Benoît sur loire ","occ":5}, "geometry": {"coordinates": [2.308, 47.81 ], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Quedlinburg","occ":7}, "geometry": {"coordinates": [11.141448, 51.792056], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Angoulême","occ":11}, "geometry": {"coordinates": [0.160000, 45.650002], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Hildesheim ","occ":7}, "geometry": {"coordinates": [9.950000, 52.150002], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Corvey","occ":5}, "geometry": {"coordinates": [9.36667 , 51.85], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Nonantola ","occ":7}, "geometry": {"coordinates": [11.041160, 44.678875], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Sankt Gallen","occ":5}, "geometry": {"coordinates": [9.376717 , 47.424482], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Cambrai  ","occ":7}, "geometry": {"coordinates": [3.235600, 50.176701], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Auxerre","occ":5}, "geometry": {"coordinates": [3.567200 , 47.424482], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Trèves","occ":7}, "geometry": {"coordinates": [6.633333, 49.750000], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Niederaltaich  ","occ":5}, "geometry": {"coordinates": [13.02317 , 48.7666], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Lobbes","occ":7}, "geometry": {"coordinates": [4.26716,50.35258], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Reichenau  ","occ":5}, "geometry": {"coordinates": [9.066007 ,47.69297], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Saint-Wandrille","occ":7}, "geometry": {"coordinates": [0.769,49.528], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Liège ","occ":6}, "geometry": {"coordinates": [5.5697 ,50.63333], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Augsbourg","occ":7}, "geometry": {"coordinates": [10.8978,48.3705], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Wissembourg  ","occ":6}, "geometry": {"coordinates": [7.9445 ,49.0369], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Hersfeld","occ":7}, "geometry": {"coordinates": [9.7020,50.8701], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Sint-Amands","occ":6}, "geometry": {"coordinates": [4.209460,51.055950], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Châlons ","occ":7}, "geometry": {"coordinates": [4.3631,48.9567], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Brauweiler","occ":6}, "geometry": {"coordinates": [6.7878,50.9589], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Bamberg","occ":7}, "geometry": {"coordinates": [10.9028,49.8988], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Dijon","occ":6}, "geometry": {"coordinates": [5.0415,47.3220], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Brescia ","occ":6}, "geometry": {"coordinates": [10.2118,45.5416], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Elst","occ":6}, "geometry": {"coordinates": [5.8474,51.9193], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Osterhofen","occ":6}, "geometry": {"coordinates": [13.0178,48.7019], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"S. Florian","occ":9}, "geometry": {"coordinates": [14.3779,48.2051], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Turin","occ":6}, "geometry": {"coordinates": [7.6869,45.0703], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Breslau","occ":16}, "geometry": {"coordinates": [17.0385,51.1079], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"San Miniato ","occ":6}, "geometry": {"coordinates": [10.8551,43.6830], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Leubus","occ":7}, "geometry": {"coordinates": [14.5375,52.4723], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Zbraslav","occ":11}, "geometry": {"coordinates": [14.3932,49.9761], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Ötz","occ":7}, "geometry": {"coordinates": [10.8966,47.2032], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Krems an der Donau","occ":7}, "geometry": {"coordinates": [15.6038,48.4100], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Zaltbommel","occ":5}, "geometry": {"coordinates": [5.2508,51.8136], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Zwolle","occ":7}, "geometry": {"coordinates": [6.0830,52.5168], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Klosterneuburg","occ":7}, "geometry": {"coordinates": [16.3238,48.3099], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Metz","occ":7}, "geometry": {"coordinates": [6.1757,49.1193], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Cluny","occ":7}, "geometry": {"coordinates": [4.6646,46.4290], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Montpellier ","occ":7}, "geometry": {"coordinates": [3.8767,43.6108], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Toulouse","occ":7}, "geometry": {"coordinates": [1.4442,43.6047], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Mersebourg ","occ":4}, "geometry": {"coordinates": [11.991746, 51.356328], "type": "Point"}}]}

]};

