var coordData = {"type":"FeatureCollection","features":[

{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Saint-Benoît sur loire ","occ":10}, "geometry": {"coordinates": [2.308, 47.81 ], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Gand","occ":5}, "geometry": {"coordinates": [3.7303, 51.0500], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Quedlinburg","occ":6}, "geometry": {"coordinates": [11.1414, 51.7921], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Hildesheim","occ":5}, "geometry": {"coordinates": [9.9580, 52.1548], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Passau","occ":6}, "geometry": {"coordinates": [13.4319, 48.5667], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Reichenau","occ":5}, "geometry": {"coordinates": [9.0609, 47.6980], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Lobbes","occ":6}, "geometry": {"coordinates": [4.2652, 50.3455], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"S. Blasien","occ":5}, "geometry": {"coordinates": [8.1281, 47.7601], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Gembloux","occ":6}, "geometry": {"coordinates": [4.6920, 50.5600], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Brauweiler","occ":5}, "geometry": {"coordinates": [6.7878, 50.9589], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Liège","occ":6}, "geometry": {"coordinates": [5.5697, 50.6330], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Augsbourg","occ":5}, "geometry": {"coordinates": [10.8978, 48.3705], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Poitiers","occ":6}, "geometry": {"coordinates": [0.3404, 46.5802], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Milan","occ":5}, "geometry": {"coordinates": [9.1900, 45.4642], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Hautmont","occ":6}, "geometry": {"coordinates": [3.9171, 50.2470], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Prague","occ":5}, "geometry": {"coordinates": [14.4378, 50.0755], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Reinhardsbrunn","occ":6}, "geometry": {"coordinates": [10.5541, 50.8711], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Melk","occ":5}, "geometry": {"coordinates": [15.3500, 48.2265], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"S. Evroult","occ":6}, "geometry": {"coordinates": [0.4601, 48.7909], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Olmütz","occ":8}, "geometry": {"coordinates": [17.2509, 49.5938], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Vérone","occ":6}, "geometry": {"coordinates": [10.9916, 45.4384], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Sazawa","occ":5}, "geometry": {"coordinates": [14.8967, 49.8716], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"S. Omer","occ":8}, "geometry": {"coordinates": [2.2522, 50.7501], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Auxerre","occ":6}, "geometry": {"coordinates": [3.5738, 47.7982], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Reims","occ":5}, "geometry": {"coordinates": [4.0317, 49.2583], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Cologne","occ":8}, "geometry": {"coordinates": [6.9603, 50.9375], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Le Bec","occ":6}, "geometry": {"coordinates": [0.7227, 49.2308], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Strasbourg","occ":5}, "geometry": {"coordinates": [7.7521, 48.5734], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Pise","occ":8}, "geometry": {"coordinates": [10.4017, 43.7228], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Utrecht","occ":6}, "geometry": {"coordinates": [5.1214, 52.0907], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Kremsmünster","occ":5}, "geometry": {"coordinates": [14.1262, 48.0544], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Klosterneuburg","occ":8}, "geometry": {"coordinates": [16.3238, 48.3099], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Nîmes","occ":6}, "geometry": {"coordinates": [4.3601, 43.8367], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Glogau","occ":5}, "geometry": {"coordinates": [16.0847, 51.6636], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Merano","occ":8}, "geometry": {"coordinates": [11.1605, 46.6618], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Lichtensteig","occ":6}, "geometry": {"coordinates": [9.0877, 47.3239], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Viktring","occ":5}, "geometry": {"coordinates": [14.2755, 46.5919], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Lucerne","occ":8}, "geometry": {"coordinates": [8.3093, 47.0502], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Padoue","occ":6}, "geometry": {"coordinates": [11.8768, 45.4064], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Foligno","occ":5}, "geometry": {"coordinates": [12.7015, 42.9509], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Cesena","occ":5}, "geometry": {"coordinates": [12.2464, 44.1396], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Tournai","occ":8}, "geometry": {"coordinates": [3.3881, 50.6055], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Opatowitz ","occ":6}, "geometry": {"coordinates": [16.67942, 49.61264], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Narbonne","occ":5}, "geometry": {"coordinates": [3.0031, 43.1843], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Paris","occ":5}, "geometry": {"coordinates": [2.3522, 48.8566], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Toulouse","occ":8}, "geometry": {"coordinates": [1.4442, 43.6047], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Montpellier ","occ":6}, "geometry": {"coordinates": [3.8767, 43.6108], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Metz","occ":5}, "geometry": {"coordinates": [6.1757, 49.1193], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Mersebourg","occ":8}, "geometry": {"coordinates": [11.991746, 51.356328], "type": "Point"}}]}

]};

var statesData = {"type":"FeatureCollection","features":[

{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Saint-Benoît sur loire ","occ":5}, "geometry": {"coordinates": [2.308, 47.81 ], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Quedlinburg","occ":7}, "geometry": {"coordinates": [11.141448, 51.792056], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Angoulême","occ":11}, "geometry": {"coordinates": [0.160000, 45.650002], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Hildesheim ","occ":7}, "geometry": {"coordinates": [9.950000, 52.150002], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Corvey","occ":5}, "geometry": {"coordinates": [9.36667 , 51.85], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Nonantola ","occ":7}, "geometry": {"coordinates": [11.041160, 44.678875], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Sankt Gallen","occ":5}, "geometry": {"coordinates": [9.376717 , 47.424482], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Cambrai  ","occ":7}, "geometry": {"coordinates": [3.235600, 50.176701], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Auxerre","occ":5}, "geometry": {"coordinates": [3.567200 , 47.424482], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Trèves","occ":7}, "geometry": {"coordinates": [6.633333, 49.750000], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Niederaltaich  ","occ":5}, "geometry": {"coordinates": [13.02317 , 48.7666], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Lobbes","occ":7}, "geometry": {"coordinates": [4.26716,50.35258], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Reichenau  ","occ":5}, "geometry": {"coordinates": [9.066007 ,47.69297], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Saint-Wandrille","occ":7}, "geometry": {"coordinates": [0.769,49.528], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Liège ","occ":6}, "geometry": {"coordinates": [5.5697 ,50.63333], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Augsbourg","occ":7}, "geometry": {"coordinates": [10.8978,48.3705], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Wissembourg  ","occ":6}, "geometry": {"coordinates": [7.9445 ,49.0369], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Hersfeld","occ":7}, "geometry": {"coordinates": [9.7020,50.8701], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Sint-Amands","occ":6}, "geometry": {"coordinates": [4.209460,51.055950], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Châlons ","occ":7}, "geometry": {"coordinates": [4.3631,48.9567], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Brauweiler","occ":6}, "geometry": {"coordinates": [6.7878,50.9589], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Bamberg","occ":7}, "geometry": {"coordinates": [10.9028,49.8988], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Dijon","occ":6}, "geometry": {"coordinates": [5.0415,47.3220], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Brescia ","occ":6}, "geometry": {"coordinates": [10.2118,45.5416], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Elst","occ":6}, "geometry": {"coordinates": [5.8474,51.9193], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Osterhofen","occ":6}, "geometry": {"coordinates": [13.0178,48.7019], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"S. Florian","occ":9}, "geometry": {"coordinates": [14.3779,48.2051], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Turin","occ":6}, "geometry": {"coordinates": [7.6869,45.0703], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Breslau","occ":16}, "geometry": {"coordinates": [17.0385,51.1079], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"San Miniato ","occ":6}, "geometry": {"coordinates": [10.8551,43.6830], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Leubus","occ":7}, "geometry": {"coordinates": [14.5375,52.4723], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Zbraslav","occ":11}, "geometry": {"coordinates": [14.3932,49.9761], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Ötz","occ":7}, "geometry": {"coordinates": [10.8966,47.2032], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Krems an der Donau","occ":7}, "geometry": {"coordinates": [15.6038,48.4100], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Zaltbommel","occ":5}, "geometry": {"coordinates": [5.2508,51.8136], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Zwolle","occ":7}, "geometry": {"coordinates": [6.0830,52.5168], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Klosterneuburg","occ":7}, "geometry": {"coordinates": [16.3238,48.3099], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Metz","occ":7}, "geometry": {"coordinates": [6.1757,49.1193], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Cluny","occ":7}, "geometry": {"coordinates": [4.6646,46.4290], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Montpellier ","occ":7}, "geometry": {"coordinates": [3.8767,43.6108], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Toulouse","occ":7}, "geometry": {"coordinates": [1.4442,43.6047], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Mersebourg ","occ":4}, "geometry": {"coordinates": [11.991746, 51.356328], "type": "Point"}}]}

]};




var prixData = {"type":"FeatureCollection","features":[

{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Princely Abbey of Corvey","occ":5}, "geometry": {"coordinates": [9.4104, 51.7782 ], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Le Bec","occ":7}, "geometry": {"coordinates": [0.7227, 49.2308], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Pisa","occ":5}, "geometry": {"coordinates": [10.4017, 43.7228 ], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Limoges","occ":5}, "geometry": {"coordinates": [1.2611, 45.8336 ], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Strasbourg","occ":7}, "geometry": {"coordinates": [7.7521, 48.5734], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Plaisance","occ":5}, "geometry": {"coordinates": [0.0488, 43.6063 ], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Liège","occ":5}, "geometry": {"coordinates": [5.5697, 50.6330 ], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Reims","occ":5}, "geometry": {"coordinates": [4.0317, 49.2583 ], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Ravenne","occ":7}, "geometry": {"coordinates": [12.2035, 44.4184], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Auxerre","occ":5}, "geometry": {"coordinates": [3.5738, 47.7982 ], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Marbach","occ":5}, "geometry": {"coordinates": [9.2646, 48.9396], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Heiligenkreuz","occ":5}, "geometry": {"coordinates": [16.1283, 48.0560], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Worms","occ":7}, "geometry": {"coordinates": [8.3507, 49.6341], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Prague","occ":5}, "geometry": {"coordinates": [14.4378, 50.0755 ], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Reggio ","occ":5}, "geometry": {"coordinates": [15.6473, 38.1113], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Brescia","occ":5}, "geometry": {"coordinates": [10.2118, 45.5416], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Constance","occ":7}, "geometry": {"coordinates": [9.1737, 47.6780], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Colmar","occ":5}, "geometry": {"coordinates": [7.3585, 48.0794 ], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Sindelfingen  ","occ":5}, "geometry": {"coordinates": [9.0044, 48.7075], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Parme","occ":5}, "geometry": {"coordinates": [10.3279, 44.8015], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Wierum","occ":7}, "geometry": {"coordinates": [6.0159, 53.4014], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Saldenhofen","occ":5}, "geometry": {"coordinates": [15.1552, 46.5653 ], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Bâle","occ":5}, "geometry": {"coordinates": [7.5886, 47.5596], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Metz","occ":5}, "geometry": {"coordinates": [6.1757, 49.1193], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Bologne","occ":7}, "geometry": {"coordinates": [11.3426, 44.4949], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Vienne","occ":5}, "geometry": {"coordinates": [16.3738, 48.2082 ], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Huy","occ":5}, "geometry": {"coordinates": [5.2396, 50.5187], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Paimpont","occ":5}, "geometry": {"coordinates": [2.1741, 48.0196], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Paris","occ":7}, "geometry": {"coordinates": [2.3522, 48.8566], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Ferrare","occ":5}, "geometry": {"coordinates": [11.6198, 44.8381 ], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Rouen","occ":5}, "geometry": {"coordinates": [1.1000, 49.4432], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Tournai","occ":5}, "geometry": {"coordinates": [3.3881, 50.6055], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Sienne","occ":7}, "geometry": {"coordinates": [11.3308, 43.3188], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Orvieto","occ":5}, "geometry": {"coordinates": [12.1107, 42.7185 ], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Klosterneuburg ","occ":5}, "geometry": {"coordinates": [16.3238, 48.3099], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Münstermaifeld","occ":5}, "geometry": {"coordinates": [7.3624, 50.2483], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Melk","occ":7}, "geometry": {"coordinates": [15.3500, 48.2265], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Berne","occ":5}, "geometry": {"coordinates": [7.4474, 46.9480], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Admont","occ":7}, "geometry": {"coordinates": [14.4615, 47.5729], "type": "Point"}}]}
]};



