var prixData = {"type":"FeatureCollection","features":[

{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Princely Abbey of Corvey","occ":5}, "geometry": {"coordinates": [9.4104, 51.7782 ], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Le Bec","occ":7}, "geometry": {"coordinates": [0.7227, 49.2308], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Pisa","occ":5}, "geometry": {"coordinates": [10.4017, 43.7228 ], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Limoges","occ":5}, "geometry": {"coordinates": [1.2611, 45.8336 ], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Strasbourg","occ":7}, "geometry": {"coordinates": [7.7521, 48.5734], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Plaisance","occ":5}, "geometry": {"coordinates": [0.0488, 43.6063 ], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Liège","occ":5}, "geometry": {"coordinates": [5.5697, 50.6330 ], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Reims","occ":5}, "geometry": {"coordinates": [4.0317, 49.2583 ], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Ravenne","occ":7}, "geometry": {"coordinates": [12.2035, 44.4184], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Auxerre","occ":5}, "geometry": {"coordinates": [3.5738, 47.7982 ], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Marbach","occ":5}, "geometry": {"coordinates": [9.2646, 48.9396], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Heiligenkreuz","occ":5}, "geometry": {"coordinates": [16.1283, 48.0560], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Worms","occ":7}, "geometry": {"coordinates": [8.3507, 49.6341], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Prague","occ":5}, "geometry": {"coordinates": [14.4378, 50.0755 ], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Reggio ","occ":5}, "geometry": {"coordinates": [15.6473, 38.1113], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Brescia","occ":5}, "geometry": {"coordinates": [10.2118, 45.5416], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Constance","occ":7}, "geometry": {"coordinates": [9.1737, 47.6780], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Colmar","occ":5}, "geometry": {"coordinates": [7.3585, 48.0794 ], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Sindelfingen  ","occ":5}, "geometry": {"coordinates": [9.0044, 48.7075], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Parme","occ":5}, "geometry": {"coordinates": [10.3279, 44.8015], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Wierum","occ":7}, "geometry": {"coordinates": [6.0159, 53.4014], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Saldenhofen","occ":5}, "geometry": {"coordinates": [15.1552, 46.5653 ], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Bâle","occ":5}, "geometry": {"coordinates": [7.5886, 47.5596], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Metz","occ":5}, "geometry": {"coordinates": [6.1757, 49.1193], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Bologne","occ":7}, "geometry": {"coordinates": [11.3426, 44.4949], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Vienne","occ":5}, "geometry": {"coordinates": [16.3738, 48.2082 ], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Huy","occ":5}, "geometry": {"coordinates": [5.2396, 50.5187], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Paimpont","occ":5}, "geometry": {"coordinates": [2.1741, 48.0196], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Paris","occ":7}, "geometry": {"coordinates": [2.3522, 48.8566], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Ferrare","occ":5}, "geometry": {"coordinates": [11.6198, 44.8381 ], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Rouen","occ":5}, "geometry": {"coordinates": [1.1000, 49.4432], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Tournai","occ":5}, "geometry": {"coordinates": [3.3881, 50.6055], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Sienne","occ":7}, "geometry": {"coordinates": [11.3308, 43.3188], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Orvieto","occ":5}, "geometry": {"coordinates": [12.1107, 42.7185 ], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Klosterneuburg ","occ":5}, "geometry": {"coordinates": [16.3238, 48.3099], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Münstermaifeld","occ":5}, "geometry": {"coordinates": [7.3624, 50.2483], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Melk","occ":7}, "geometry": {"coordinates": [15.3500, 48.2265], "type": "Point"}}]},
{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Berne","occ":5}, "geometry": {"coordinates": [7.4474, 46.9480], "type": "Point"}}]},

{"type":"FeatureCollection","features":[{"type": "Feature","properties":{"name":"Admont","occ":7}, "geometry": {"coordinates": [14.4615, 47.5729], "type": "Point"}}]}
]};

